### ISSUE TITLE
Option to change Parameters 

### ISSUE THREAD

**Issue by sfc-gh-mgohl** [MobilizeNet/SnowConvert_Support_Library#29]
There is not an option to change the behavior of quoted identifier or timestamp type mapping
    
    Suggest that the program uses the account settings and provide the ability to override the accounts at run time.

Current code:
    cur.execute("set quoted_identifiers_ignore_case = TRUE")
    cur.execute("alter session set TIMESTAMP_TYPE_MAPPING = TIMESTAMP_LTZ")

**Comment by orellabac** [comment]
We removed this hardcoded params
